@startuml StateUML
[*] --> Пользователь_начал_сессию : "Пользователь заходит на сайт"
[*] --> Пользователь_зарегистрирован: "Пользователь заходит в бота и регистрируется"
Пользователь_начал_сессию --> Пользователь_имеет_список_избранного : "Пользователь добавляет блюда в избранное"
Пользователь_начал_сессию --> Пользователь_сформировал_заказ : "Заказ понравившихся блюд через сортировки и фильтры"
Пользователь_имеет_список_избранного --> Пользователь_сформировал_заказ : "Заказ понравившихся блюд через сортировки и фильтры"
Пользователь_сформировал_заказ --> [*]
Пользователь_сформировал_заказ --> Пользователь_сформировал_заказ : "Перезаказ"
Пользователь_сформировал_заказ --> Пользователь_имеет_настроенный_автозаказ : "Пользователь включает автозаказ"
Пользователь_имеет_настроенный_автозаказ --> [*]
Пользователь_имеет_настроенный_автозаказ --> Пользователь_зарегистрирован : "Регистрация в телеграмм-боте"
Пользователь_зарегистрирован --> Пользователь_имеет_подключенную_функцию : "Подключение функции подтверждения автозаказа"
Пользователь_имеет_подключенную_функцию --> [*]
@enduml
