@startuml
|Сотрудник|
start

:Выбор себя из списка сотрудников;

|Система|

if (Заказ или автозаказ?) then (Заказ)
    |Сотрудник|
    :Поиск блюд;
    :Применение фильтров;

    |Система|
    :Фильтрация по названию блюда;
    :Ограничение по белкам/жирам/углеводам/калориям; по цене; по типу блюда; по лайкам;

    :Сортировка блюд: избранное, по цене;

    :Просмотр карточки блюда (состав, БЖУ, картинка, отзывы);

    if (Изменение состава заказа?) then (да)
        :Изменение состава заказа;
    endif

    :Подтверждение заказа;

else (Автозаказ)
    |Сотрудник|
    :Настройка автозаказа по дням недели;

    |Система|
    :Выбор опций автозаказа;

    if (Избранные) then (Да)
        :Автосборка на основе избранных блюд;
    else (Нет)
        if (Заказанные) then (Да)
            :Автосборка на основе заказанных блюд (по умолчанию);
        else (Нет)
            :Случайная автосборка;
        endif
    endif

    if (Ограничения на бюджет?) then (Заданный бюджет)
        :Ограничиться заданным бюджетом;
    else (Обычный бюджет)
        :Ограничиться обычным бюджетом (по умолчанию);
    endif

    |Система|
    :Подтверждение настройек автозаказа;

endif

|Система|
:Отправка заказа в отчет поставщикам;

stop
@enduml